name: Generate Javadoc

on:
  push:
    branches: [ "main", "setup-javadoc" ]

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Generate Javadoc
      run: ./gradlew generateReleaseJavadoc

    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: Update Javadoc
        add: 'doc/javadoc'

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        clean: true
        folder: doc/javadoc
        target-folder: javadoc
