name: Generate Javadoc

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'doc/**'

jobs:
  generate_javadoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --parallel

    - name: Generate Javadoc
      run: ./gradlew generateReleaseJavadoc

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        add-paths: doc/javadoc
        body: Automated Update Javadocs
        branch: docs-update-javadoc
        commit-message: "docs: update javadocs"
        delete-branch: true
        title: "Docs: Update Javadocs"
